---
- name: Konfiguriere UFW Firewall
  hosts: all
  become: true

  tasks:
    - name: Entferne alle vorhandenen UFW-Regeln
      community.general.ufw:
        state: reset

    - name: Erlaube HTTP (Port 80)
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: Erlaube HTTPS (Port 443)
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: Erlaube gesamten Traffic von spezifischen IPs
      community.general.ufw:
        rule: allow
        from_ip: "{{ item }}"
      loop: "{{ lookup('env', 'ALLOWED_IPS') | split(',') }}"

    - name: Aktiviere UFW Firewall
      community.general.ufw:
        state: enabled
