---
- name: Configure UFW firewall on Ubuntu server
  hosts: all
  become: true

  tasks:
    - name: Install UFW if not present
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Reset UFW (remove all existing rules)
      ufw:
        state: reset

    - name: Set default policy to deny all incoming traffic
      ufw:
        default: deny
        direction: incoming

    - name: Allow full access to specified IPs (TCP and UDP)
      ufw:
        rule: allow
        from_ip: "{{ item }}"
        port: any
        proto: any
      with_items: "{{ lookup('env', 'ALLOWED_IPS') | split(',') }}"

    - name: Allow HTTP (Port 80) and HTTPS (Port 443) for all
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      with_items:
        - '80'
        - '443'

    - name: Enable UFW
      ufw:
        state: enabled
        direction: incoming

    - name: Reload UFW to apply changes
      ufw:
        state: reloaded
